### PR TITLE
Updated DistTask.yml / Add support for macos_ARM64 builds

### PR DESCRIPTION
**Pull request by cmaglie**
The updated [`DistTask.yml`](https://github.com/arduino/arduino-cli/blob/65fb6e5e839b9bd7692306f17ed37da464a8c9c3/DistTasks.yml) has been taken from the Arduino CLI project.

### CODE REVIEW

**Comment by cmaglie** [comment]
I've made a test build and it seems working as expected.

**Comment by umbynos** [comment]
Are we 100% sure that CGO is not required? Have you tested if the monitor works correctly on linux/macos?

**Review by alessio-perugini — APPROVED** [review]
I've tested on Linux and it's working fine. At the moment I don't have other OSs to test it.

**Comment by cmaglie** [comment]
> Are we 100% sure that CGO is not required? Have you tested if the monitor works correctly on linux/macos?

Yes, CGO is needed only for the USB enumerator on macOS.
Here we only use the serial port, we don't need the enumerator, and no CGO is needed!

**Review by umbynos — APPROVED** [review]

**Pull request merged**
